Feature/is 144 org identities
swedenconnect/technical-framework pull request #145
Opened 2021-02-10 14:10 UTC by martin-lindstrom

Changes for organizational eID:s.

2021-02-12 09:54 UTC, Razumain requested changes
Only a few comments

2021-02-12 09:54 UTC, Razumain commented on 04 - Attribute Specification for the Swedish eID Framework.md
> +
There is a new section 3.2.5 specifying the requirements on the content of this attribute. It is perhaps not great to express requirements (MUST) in this note in addition to 3.2.5. It will make this document harder to maintain as requirements gets spread and duplicated in several places. I'd suggest placing all requirements in 3.2.5 and to just keep a short explanatory reference here without requirements language.

2021-02-15 14:05 UTC, martin-lindstrom commented on 02 - Deployment Profile for the Swedish eID Framework.md
> +
I agree

2021-02-15 14:11 UTC, martin-lindstrom commented on 04 - Attribute Specification for the Swedish eID Framework.md
> +
Fixed

2021-02-15 15:58 UTC, merged