IS-153: Introduction of scoped attributes
swedenconnect/technical-framework pull request #156
Opened 2021-09-15 13:56 UTC by martin-lindstrom

We added rules for "scoped attributes". Currently, this applies to the orgAffiliation attribute.

2021-09-20 23:35 UTC, Razumain requested changes

2021-09-20 23:35 UTC, Razumain commented on 04 - Attribute Specification for the Swedish eID Framework.md
> +
How can a relying party (SP) determine that such "attribute policy" is governing the attribute release or not? This seems to be vital considering the requirement/recommendation related to validation of scoped attributes.

2021-09-20 23:35 UTC, Razumain commented on 04 - Attribute Specification for the Swedish eID Framework.md
The MUST is problematic again. In particular if the SP may not know if an attribute is scoped or not from information in the assertion or from information in metadata. 

You may want to add that the SP also need to determined which scoped values that are relevant for each scoped attribute. For example, if an IdP has scoped "example.com" and "5511223456" this does not allow the orgAffiliation john@example.com, nor does it allow the illegal e-mail john@5511223456.

It may also be relevant to advice the relying party (SP) about the correct action if a scoped attribute is received from an IdP that has no scope declaration in metadata. For example if e-mail john.doe@example.com is returned but not scoping of example.com. Should this be rejected or accepted (as there probably is no attribute policy in place) ?

2021-09-21 15:26 UTC, martin-lindstrom commented on 04 - Attribute Specification for the Swedish eID Framework.md
> +
My idea was that this would be covered in a documented attribute set. But I'll make a change to indicate that the mail attribute should be regarded as non-scoped if not explicitly documented by an active attribute set.

2021-09-22 15:01 UTC, Razumain approved these changes

2021-09-22 15:05 UTC, merged