IS-178 Defined more authContext URIs and modified service categories
swedenconnect/technical-framework pull request #179
Opened 2021-11-09 17:18 UTC by martin-lindstrom

Added authentication context URIs for uncertified providers and for non-resident eID holders.

Also modified the definition of service entity categories allowing the official LoA URI as well as variants of it (uncertified, non-resident).

Closes #178

2021-11-09 21:24 UTC, fredriklj commented on 03 - Registry for Identifiers.md
> +| `http://id.swedenconnect.se/loa/1.0/`<br/>`loa4-nonresident` | A URI that is indented to be used by a level 4-certified providers that authenticate a non-resident eID holder according to assurance
Loa 4 för non-residents existerar inte i den tänkta tillämpningen. Man kan fundera på om man ska ha den med ändå för att vara framtidssäker? Eller så för man dit den om den behövs.

2021-11-09 21:29 UTC, fredriklj commented on 03 - Registry for Identifiers.md
> +> [Tillitsramverk för kvalitetsmärket Svensk e-legitimation](https://www.digg.se/digital-identitet/e-legitimering/tillitsnivaer/tillitsramverket).
Jag vet att de DIGG har prefixat "kvalitetsmärket" på 51 ställen i tillitsramverket, men det kommer åka väck i nästa revision. Eftersom tillitsramverket tillämpas även utan kvalitetsmärket, för loa2 t.ex.

Föreslår därför att vi håller oss till den traditionella benämningen "Tillitsramverket för Svensk e-legitimation".

2021-11-09 21:29 UTC, fredriklj commented on 06 - Entity Categories for the Swedish eID Framework.md
> +> [Tillitsramverk för kvalitetsmärket Svensk e-legitimation](https://www.digg.se/digital-identitet/e-legitimering/tillitsnivaer/tillitsramverket).
Ta bort "kvalitetsmärket".

2021-11-09 21:29 UTC, fredriklj commented on 06 - Entity Categories for the Swedish eID Framework.md
> +> Or a corresponding LoA 4 URI (see section 3.1.1 of \[[EidRegistry](#eidregistry)\].
Osäker på om det finns varianter av loa4? Varken självdeklarerar eller non-residents..

2021-11-10 10:42 UTC, martin-lindstrom commented on 03 - Registry for Identifiers.md
> +| `http://id.swedenconnect.se/loa/1.0/`<br/>`loa4-nonresident` | A URI that is indented to be used by a level 4-certified providers that authenticate a non-resident eID holder according to assurance
Givet att en eID-leveratör som ska kunna leverera enligt "eID för medarbetare" är anmäld för både LoA 3 och 4 så borde det väl vara relevant redan nu?

2021-11-10 10:43 UTC, martin-lindstrom commented on 03 - Registry for Identifiers.md
> +> [Tillitsramverk för kvalitetsmärket Svensk e-legitimation](https://www.digg.se/digital-identitet/e-legitimering/tillitsnivaer/tillitsramverket).
OK

2021-11-10 10:44 UTC, martin-lindstrom commented on 06 - Entity Categories for the Swedish eID Framework.md
> +> Or a corresponding LoA 4 URI (see section 3.1.1 of \[[EidRegistry](#eidregistry)\].
Non-residents (enligt tidigare kommentar).

2021-11-10 11:02 UTC, Razumain requested changes
Mycket bra i stort. Små kommentarer

2021-11-10 11:02 UTC, Razumain commented on 06 - Entity Categories for the Swedish eID Framework.md
> +
Samma som ovan (om vi ändrar enligt mitt förslag)

2021-11-10 12:41 UTC, martin-lindstrom commented on 03 - Registry for Identifiers.md
Jo, fast för övriga så har ju en granskning gjorts. Men jag tar bort texten. Det framgår vad som avses i ingressen.

2021-11-10 12:46 UTC, fredriklj commented on 06 - Entity Categories for the Swedish eID Framework.md
> +> Or a corresponding LoA 4 URI (see section 3.1.1 of \[[EidRegistry](#eidregistry)\].
Med det beslut som finns för non-residents, så gäller detta för loa2 och 3. Inte 4.

2021-11-10 12:49 UTC, martin-lindstrom commented on 06 - Entity Categories for the Swedish eID Framework.md
> +> Or a corresponding LoA 4 URI (see section 3.1.1 of \[[EidRegistry](#eidregistry)\].
Jo, men tekniskt ramverk är rätt avhängigt de avtal som DIGG tecknar. Och det skadar inte att förbereda. Dessutom undrar jag hur det beslutet togs, men det kan vi ta separat.

2021-11-10 13:10 UTC, fredriklj commented on 06 - Entity Categories for the Swedish eID Framework.md
> +> Or a corresponding LoA 4 URI (see section 3.1.1 of \[[EidRegistry](#eidregistry)\].
Helt med på att det kan vara bra att förbereda, ni avgör.

2021-11-10 13:24 UTC, merged