IS-199 Spec identity binding june 2023
swedenconnect/technical-framework pull request #200
Opened 2023-06-07 16:16 UTC by araskazemi

Please se suggested updates for identity binding.

2023-06-08 07:49 UTC, martin-lindstrom requested changes
Partial review. Still some things to check ...

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +identification number (a.k.a. personnummer) or the Swedish coordination
We normally write "Swedish personal identity number".

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +number (a.k.a. samordningsnummer) as identifier to carry out the
"as identifier to carry out the" -> "as the primary identity attribute to carry out the"

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +authorisation of the authenticated user. These records cannot be found
"These records cannot be found in eIDAS attributes" -> "These attributes are not part of an eIDAS assertion".

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +The Identity Binding Service is an extension to Swedish eIDAS-node and
Well. It's not an extension. We need a re-wording here.

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +authenticated through eIDAS, in those cases when:
"in those cases when" -> "in the following cases"

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +- end-user have a registered record in terms of Swedish personal identification number (a.k.a. personnummer) or the Swedish coordination number (a.k.a. samordningsnummer) in the Swedish population re
**the** end-user

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +When end-user's Swedish records are linked to her/his eID, the Swedish eIDAS-node can
When **the** end-user's

to **the** relying party.

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +See also sections 2.5, "eIDAS Natural Person Attribute Set", and 3.3.2, "The mappedPersonalIdentityNumber and personalIdentityNumberBinding Attributes", of [Attribute Specification for the Swedish eI
Don't include link to updates. Always use latest.

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +Linked identifications through the Identity Binding Service can be provided in three different levels of confidence.
I don't like: "Linked identifications". It is not a identification. Its a binding of identities.

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +### 3.1. Basic Binding (A)
A?

2023-06-08 07:49 UTC, martin-lindstrom commented on Identity Binding.md
> +Following processes must have been applied:
**The** following

2023-06-08 12:21 UTC, araskazemi commented on Identity Binding.md
> +# Binding of eIDAS identity to records in the Swedish population register
record can be Swedish Personal Identity Number (a.k.a. personnummer) or Coordination Number (a.k.a. samordningsnummer)

2023-06-08 12:27 UTC, araskazemi commented on Identity Binding.md
> +### 3.1. Basic Binding (A)
A, B, C is used in the end-user UI aimed at avoiding situations in translations that can cause missunderstanding...

2023-06-09 15:07 UTC, martin-lindstrom approved these changes
Made some language fixes ...

2023-06-09 15:07 UTC, merged